nWidart/laravel-modules

config/config.php
src/Commands/GenerateEventCommand.php
src/Commands/GenerateListenerCommand.php
src/Commands/stubs/event.stub
src/Commands/stubs/listener.stub
src/Providers/ConsoleServiceProvider.php
tests/Commands/GenerateEventCommandTest.php
tests/Commands/GenerateListenerCommandTest.php

They follow the same convention as the default commands artisan ships with, e.g the Listener command requires an `--event` option to be present.

Addded Event and Listener Generation Commands

---

src/Commands/SeedCommand.php

Right now, it's impossible to use the mode:seed command without interactions in a production environment.
The changes make it possible. :)

Added force option to module:seed command

---

src/Providers/ConsoleServiceProvider.php

`$this->commands()` will accept an array and do the loop itself.
`provides()` returns an array, which the commands are already in.

Remove unnecessary loops in register and provides

---

src/Commands/MigrateCommand.php
src/Commands/PublishMigrationCommand.php
src/Commands/SeedCommand.php
src/Migrations/Migrator.php
src/Publishing/MigrationPublisher.php

Refactored the "module:seed" command logic in order to reduce code duplication.
Fixed an existing bug which would cause the "module:migrate" command to throw an offset warning if the --seed option is specified.  
Fixed a newly introduced bug(my bad) where the SeedCommand:dbseed() method would append the base module namespace to the FQN of a seeder class.  This would only occur if the user had provided an explicit classname using the optional "migration.seeds" argument.  
Removed the "class option" from "module:seed" since it should logically only be set from within the dbSeed($class) method which in turn issues each of these calls directly to the "db:seed" command.  
Removed the "all option" from "module:seed" since it actually wasn't being used for anything. 
ie: The existing behavior …

Fixed a number of bugs in the module:migrate + module:seed commands

---

src/Repository.php

Remove a frist slash.
Before fixed:
```
Module::asset('system:css/app.css');
// http://localhost:8000/\modules/system/css/app.css
```
After fixed:
```
Module::asset('system:css/app.css');
// http://localhost:8000/modules/system/css/app.css
```

Fixed Module::asset();

---

src/Commands/MigrateResetCommand.php
src/Commands/MigrateRollbackCommand.php

Based on #96, commands like `module:migrate-rollback` and `module:migrate-reset` does not respect order parameter of modules as `module:migrate` does.
Also instead of all modules it will run only on enabled ones.
Added `--direction`/`--d` command to both commands defaulting to `desc` (all enabled modules in reverse order).

Respect module order in reverse migrations

---

README.md
src/Repository.php
tests/ModuleFacadeTest.php

At my job, we use this library a lot in a very large project, and if there's one thing that would be extremely useful in creating custom functionality that extends your library, it's being able to define custom macros onto the repository.
This PR adds two tests for the Macroable trait, and adds the Macroable trait to the repository.

Add Macroable trait to module repository

---

src/Commands/ListCommand.php

From the discussion of https://github.com/nWidart/laravel-modules/issues/160

Change list command to give the name of the module, not the studly cased form

---

src/Migrations/Migrator.php

When manually running the `->log()` method externally (public ACL) it fails as it tries to call the `getNextBatchNumber()` without a parameter.

Making the $migrations parameter optional on getLastBatchNumber()

---

src/Commands/MigrateCommand.php

Adds a subpath option to the migrate command so the user can structure different migrations per folders

Add a subpath option to migrate command

---

composer.json

Tried using this with `5.5-*` and found it wouldn't install. Added `5.5.*` to the required versions list and everything worked fine with using my forked branch as the Composer repository / source.

added 5.5.* to required list of Laravel versions

---

src/Collection.php
src/Module.php
tests/ModuleTest.php

The project I work on has various instances of the codebase, with modules enabled and disabled according to client needs. To avoid conflicts, we do not have the module.json checked into the project repo, but rather manage those files through some custom logic in Laravel. The changes introduced in 1.25 force modules to have a valid json file when they are initialized, which means that there is never a chance for Laravel to act on any undeployed module configs, since the missing files trigger a File Missing exception.
This PR solves this problem by moving the json requirement back into `json()`, and additionally improves performance by also caching any other files requested.

Revise json cache

---

src/LaravelModulesServiceProvider.php
src/LumenModulesServiceProvider.php
src/Module.php
src/ModulesServiceProvider.php
src/Repository.php

Support for Lumen:
- Instead of injecting laravels application refactored to Illuminate\Container\Container that is extentend by both laravels and lumen applications.
- In Lumen case namespaces ( haven't tested on laravel since I left it as it is ) must be loaded before registering module provider since it needs some configuration values. Loading these in boot() method will fail to init provider.
- Requested changes from old PR.

Lumen support

---

composer.json
src/Module.php
tests/ModuleTest.php

It would be helpful to be able to hook into a specific event when a module is enabled or disabled. This changes these events to simply call the already existing `fireEvent` which I figured would help standardize the event names.

adds module name to disable/enable events, further standardizes events

---

src/Commands/stubs/scaffold/provider.stub

Previously, app was search for factories in `Module/Providers/Database/factories` instead of `Module/Database/factories`

Fix wrong path for registerFactories() in prvoider.stub

---

src/Commands/MakeFactoryCommand.php
src/Commands/stubs/factory.stub
src/Providers/ConsoleServiceProvider.php
tests/Commands/MakeFactoryCommandTest.php

So far it does not support `--model` argument; just a stub
Path is not configurable since there are already some places ([service provider stub](https://github.com/nWidart/laravel-modules/blob/master/src/Commands/stubs/scaffold/provider.stub#L99)), where `/Database/factories` path is hard-coded, thus possible BC.
---
Made new issue for content that was here.

Fix #338, introduce command for creating factories

---

src/Commands/stubs/scaffold/provider.stub
tests/Commands/__snapshots__/ModuleMakeCommandTest__it_generates_correct_service_provider_content__1.php
tests/Commands/__snapshots__/ModuleMakeCommandTest__it_generates_module_namespace_using_studly_case__1.php
tests/Commands/__snapshots__/ModuleMakeCommandTest__it_generates_module_resources__1.php
tests/Commands/__snapshots__/ProviderMakeCommandTest__it_can_change_the_default_namespace__1.php
tests/Commands/__snapshots__/ProviderMakeCommandTest__it_can_have_custom_migration_resources_location_paths__1.php
tests/Commands/__snapshots__/ProviderMakeCommandTest__it_generates_a_master_service_provider_with_resource_loading__1.php

for easy calling from artisan like
```
php artisan vendor:publish --provider="YourNamespace\YourServiceProvider" --tag="views"
```

added views tag to ServiceProvider stub

---

src/Commands/stubs/route-provider.stub
tests/Commands/__snapshots__/RouteProviderMakeCommandTest__it_can_change_the_default_namespace__1.php
tests/Commands/__snapshots__/RouteProviderMakeCommandTest__it_generated_correct_file_with_content__1.php

Modules\XXX\Providers\RouteServiceProvider is stubbed with `before()` that isn't actually called. Changing this to `boot()`.
Discussed in https://github.com/nWidart/laravel-modules/issues/424

RouteProvider stub - use boot() instead of before()

---

src/Laravel/Repository.php
src/Lumen/Repository.php
src/Repository.php

`Lumen/Repository.php` and `Laravel/Repository.php` were exact copies. It was unnecessary code duplication. I  moved `scan` and `formatChached` function back to the abstract parent repository.

Remove code duplication

---

src/Repository.php

by default, scan path includes all modules from vendor folder via `vendor/*/*` path
```php
'scan' => [
'enabled' => false,
'paths' => [
base_path('vendor/*/*'),
],
],
```
But `str_finish` convert the path to `vendor/*` because it removes all `/*` from path to force add only one `/*` in the end, and this cause module doesn’t load from vendor folder, so this PR to check if path end with `/*` already skip adding `/*` to the end.

fixed modules don't load from vendor folder

---

config/config.php
src/Module.php

in some situations, files of the module need to access to config of the module, but right now files include in the register method when config of modules doesn’t load yet ( it's will be available only if Laravel config is cached)
So, I think included files is best to load on boot function to ensure config of modules will be available.
by default will be included files on register method but can change this behavior from config of package `config/modules.php`
```php
/*
|--------------------------------------------------------------------------
| Choose what laravel-modules will register as custom namespaces.
| Setting one to false will require you to register that part
| in your own Service Provider class.
|--------------------------------------------------------------------------
*/ …
```

include files while booting app.

---

src/Support/Stub.php
tests/StubTest.php
tests/stubs/model.stub

If somebody overrides stub path in the config, he should copy new stubs with every new release of the package to add missing stub,
This PR fixes this problem by check if stub file exists on override path use it or use default stub form package folder as a fallback.
I add some test unit for that to make sure everything is work.
thanks

use default stub if override not exists

---

src/Commands/SeedCommand.php

When a row in the database doesn't exist, you get a 
A non well formed numeric value encountered
This is because you're catching an exception rather than throwable

Fix non well formed numeric value

---

src/Commands/SetupCommand.php

If you provide a more deep path than default, it will fail if any folder parent doesn't exists.
So a simple commit to fix that

Generate folders recursively

---

src/Commands/SeedCommand.php

This changes allows use `--class` option to specify a specific seeder class to run individually.
Example:
`php artisan module:seed User --class=Modules\User\Database\Seeders\UserRoleDatabaseSeeder`.

Returns the parameter `--class` to the `SeedCommand`.

---

src/Module.php
tests/LaravelModuleTest.php

I couldn't figure out what was gravitano's rational behind using `realpath()` when constructing a `Module` class. It seems unnecessary to me. It wouldn't be an issue though, but this caused me trouble when I added modules behind symlinks, as `realpath` returns an absolute path with resolved symlinks. Removing `realpath` doesn't seem to break anything, but solves my issue.

Allow symlinks in module path

---

src/Commands/SeedCommand.php
src/Commands/SeedMakeCommand.php
src/Commands/stubs/seeder.stub

Error before: 
`Type error: Argument 1 passed to Nwidart\Modules\Commands\SeedCommand::reportException() must be an instance of Exception, instance of Error given, called in /home/vagrant/sites/pq/ vendor/nwidart/laravel-modules/src/Commands/SeedCommand.php on line 50`
- plus -
add namespace to config('seeder') custom

Fix Issues #465 Add namespace for custom config seeder path

---

src/Commands/stubs/package.stub
src/Commands/stubs/views/master.stub
src/Commands/stubs/webpack.stub
tests/Commands/__snapshots__/ModuleMakeCommandTest__it_generates_webpack_file__1.php

- Fix css relative urls by changing the route folder
- Prevents every build from deleting previous Mix config file
I used custom [extension](https://github.com/KABBOUCHI/laravel-mix-merge-manifest) to fix the second issue, I'll remove it once Laravel Mix merges this [PR#1453](https://github.com/JeffreyWay/laravel-mix/pull/1453)

Fix Laravel Mix

---

src/Module.php
tests/BaseTestCase.php

~There other test failures for the events, I'll check them later.~
I found the problem, while ago they changed the $event->fire to $event->dispatch, they remove it completely in 5.7

[5.7] disable mocking the console output & fix events

---

src/LaravelModulesServiceProvider.php
src/LumenModulesServiceProvider.php
src/ModulesServiceProvider.php
tests/LaravelModulesServiceProviderTest.php

Allows developers to do: `app(‘modules’)->someMethod();` and `app(FileRepository::class)->someMethod();`
This is the same as PR #621, but for v3 of Laravel Modules.

Allow class resolution on short name and abstract

---

src/Commands/SeedCommand.php

This adds the seeding ability to modules located in scans.paths config paths.
ie:
```
'scan' => [
'enabled' => true,
'paths' => [
base_path('ModulesCms'),
],
],
```
The default running order remains the same if no modules are found in the Module namespace then any namespaces defined in the config will be tried.

Seeding modules not in Modules namespace.

---

src/Commands/stubs/route-provider.stub
tests/Commands/__snapshots__/ModuleMakeCommandTest__it_generates_module_resources__4.php
tests/Commands/__snapshots__/RouteProviderMakeCommandTest__it_can_change_the_default_namespace__1.php
tests/Commands/__snapshots__/RouteProviderMakeCommandTest__it_generated_correct_file_with_content__1.php

The stubbed RouteProvider extends `Illuminate\Foundation\Support\Providers\RouteServiceProvider` setting the `$namespace` property means that on each `boot()` of a module's RouteServiceProvider we are changing the URL generator's root namespace.  
I believe this should be controlled by the application level RouteServiceProvider only.
See `Illuminate\Foundation\Support\ProvidersRouteServiceProvider::setRootControllerNamespace`

Update Route Provider stub to not affect the root namespace of the URL generator

---

src/Commands/stubs/scaffold/provider.stub
tests/Commands/__snapshots__/ModuleMakeCommandTest__it_generates_module_namespace_using_studly_case__1.php
tests/Commands/__snapshots__/ModuleMakeCommandTest__it_generates_module_resources__1.php
tests/Commands/__snapshots__/ProviderMakeCommandTest__it_can_change_the_default_namespace__1.php
tests/Commands/__snapshots__/ProviderMakeCommandTest__it_can_have_custom_migration_resources_location_paths__1.php
tests/Commands/__snapshots__/ProviderMakeCommandTest__it_generates_a_master_service_provider_with_resource_loading__1.php

I think this approach can reduce the application to load the unused file when running in browser.

Only Register Factories when Running in Console

---

src/Support/Migrations/SchemaParser.php
tests/Commands/MigrationMakeCommandTest.php
tests/Commands/__snapshots__/MigrationMakeCommandTest__it_generates_foreign_key_constraints__1.php

Support a Foreign Key Constraints (https://laravel.com/docs/5.8/migrations#foreign-key-constraints), use --fields=belongsTo: foreign: references: on.
Exemple:
Command: ```php artisan module:make-migration create_post_table --fields=belongsTo:user:id:users```
Result:
```
Schema::create('post', function (Blueprint $table) {
$table->increments('id');
$table->integer('user_id')->unsigned();
$table->foreign('user_id')->references('id')->on('users');
$table->timestamps();
});
```

Support a Foreign Key Constraints

---

config/config.php

Change the default path for the statuses file for the FileActivator to the `app` folder in the storage folder. This to keep the application's storage folder clean.
Point of discussion; maybe add modules folder in storage and include files like this in there? The files app folder get git ignored by default.

Change the fileactivator status file path

---

src/helpers.php
tests/HelpersTest.php

Extends the module_path helper with an optional $path parameter to be able to parse a relative path together with the module path. I.E.:
```
$myModuleConfig = module_path('MyModule', 'config/config.php');
```
And fix the codestyle of the other path helpers.

Fix codestyle of path helpers and extend the module_path helper

---

.github/workflows/php.yml

This PR updates `ppa:ondrej/php` before updating `Xdebug`, so that latest version can be installed.

Update ppa:ondrej/php before updating Xdebug

---

src/Commands/stubs/scaffold/provider.stub
tests/Activators/__snapshots__/FileActivatorTest__it_creates_valid_json_file_after_disabling__1.php
tests/Activators/__snapshots__/FileActivatorTest__it_creates_valid_json_file_after_disabling__2.php
tests/Activators/__snapshots__/FileActivatorTest__it_creates_valid_json_file_after_enabling__1.php
tests/Activators/__snapshots__/FileActivatorTest__it_creates_valid_json_file_after_enabling__2.php
tests/Commands/__snapshots__/ModuleMakeCommandTest__it_generates_module_namespace_using_studly_case__1.php
tests/Commands/__snapshots__/ModuleMakeCommandTest__it_generates_module_resources__1.php
tests/Commands/__snapshots__/ProviderMakeCommandTest__it_can_change_the_default_namespace__1.php
tests/Commands/__snapshots__/ProviderMakeCommandTest__it_can_change_the_default_namespace_specific__1.php
tests/Commands/__snapshots__/ProviderMakeCommandTest__it_can_have_custom_migration_resources_location_paths__1.php
tests/Commands/__snapshots__/ProviderMakeCommandTest__it_generates_a_master_service_provider_with_resource_loading__1.php

The previous stub copied a lot of `'$MODULE$'` and `'$LOWER_NAME$'` into the scaffold, which imho introduces bugs more easily when you have to rename a module after creating a new one. This setup is a little bit cleaner.
I didn't bother to change the other placeholders as properties, since those weren't copied as frequently.
Run `php artisan module:make TestModule` and check the outputs of the generated `TestModuleServiceProvider.php`.

Make properties of frequently used scaffolding placeholders

---

src/Commands/stubs/webpack.stub
tests/Commands/__snapshots__/ModuleMakeCommandTest__it_generates_webpack_file__1.php

When trying to use Echo in app.js, it miss the `process.env.MIX_*` values, this PR register them and allow to use usual calls like the one commented out in the main Laravel project
```js
window.Echo = new Echo({
broadcaster: 'pusher',
key: process.env.MIX_PUSHER_APP_KEY,
cluster: process.env.MIX_PUSHER_APP_CLUSTER,
encrypted: true
});
```

populate process.env vars to allow Echo usage

---

src/Commands/stubs/resource.stub
tests/Commands/__snapshots__/ResourceMakeCommandTest__it_generated_correct_file_with_content__1.php

This PR. fixes the namespace of the json resource. see [#22969](https://github.com/laravel/framework/pull/22969)

Update JsonResource namespace

---

src/Commands/stubs/composer.stub
tests/Commands/__snapshots__/ModuleMakeCommandTest__it_generates_correct_composerjson_file__1.php
tests/Commands/__snapshots__/ModuleMakeCommandTest__it_generes_module_with_new_provider_location__2.php

Having the service provider in composer.json causes Laravel to auto detect it. This change stops this from happening

Removing module service provider from composer.json stub

---

src/LaravelModulesServiceProvider.php

Current version of laravel-modules doesn't work custom stub path because of LaravelModulesServiceProvider used fixed path on line number 35.
```
Stub::setBasePath(__DIR__ . '/Commands/stubs');
```
Replace above code with this code then it works fine.
```
$path = $this->app['config']->get('modules.stubs.path') ?? __DIR__ . '/Commands/stubs';
Stub::setBasePath($path);
```

Fixed custom stub path issue.

---

src/Laravel/Module.php

Hi @nWidart !
We had the problem last week that our deployments on Laravel Vapor went down multiple times with the same error message again and again. This caused about 30k messages in Sentry exception logging for us and a few hours of deep diving into the code 😅
**The problem:**
```
Exception: The /var/task/bootstrap/cache directory must be present and writable.
#28 /vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(190): Illuminate\Foundation\ProviderRepository::writeManifest
#27 /vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(165): Illuminate\Foundation\ProviderRepository::compileManifest
#26 /vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(61): Illuminate\Foundation\ProviderRepository::load
#25 …
```

Custom cache path for Laravel Vapor deployed app

---

src/Commands/ListenerMakeCommand.php
tests/Commands/ListenerMakeCommandTest.php
tests/Commands/__snapshots__/ListenerMakeCommandTest__it_generated_correct_queued_event_in_a_subdirectory_with_content__1.php
tests/Commands/__snapshots__/ListenerMakeCommandTest__it_generated_correct_queued_event_with_content__1.php
tests/Commands/__snapshots__/ListenerMakeCommandTest__it_generated_correct_sync_event_in_a_subdirectory_with_content__1.php
tests/Commands/__snapshots__/ListenerMakeCommandTest__it_generated_correct_sync_event_with_content__1.php

This PR fixes issue #1017 where the Event class namespace should depend on the Event path set in the config file. Also added support for Event classes placed on sub-directories.

Refactor ListenerMakeCommand

---

.gitignore
src/Commands/FactoryMakeCommand.php
src/Commands/stubs/factory.stub
src/Commands/stubs/model.stub
tests/Commands/FactoryMakeCommandTest.php
tests/Commands/__snapshots__/FactoryMakeCommandTest__it_makes_factory__1.php
tests/Commands/__snapshots__/ModelMakeCommandTest__it_can_change_the_default_namespace__1.php
tests/Commands/__snapshots__/ModelMakeCommandTest__it_can_change_the_default_namespace_specific__1.php
tests/Commands/__snapshots__/ModelMakeCommandTest__it_generated_correct_file_with_content__1.php
tests/Commands/__snapshots__/ModelMakeCommandTest__it_generates_correct_fillable_fields__1.php

changed the `module:make-factory` argument description from `ModelFactory` to `Model` that way the command generates a factory with a model name rather that a factory name as argument

added Laravel 8 compatible Factory and Model generation

---

config/config.php

This PR fixes the issue with these commands not getting registered:
`module:make-component <name> <module>` 
`module:make-component-view <name> <module>`

Fix missing commands

---

src/Commands/RuleMakeCommand.php

**before:** 
```
php artisan module:make-rule phone-number Test
namespace Modules\Test\Rules;
use Illuminate\Contracts\Validation\Rule;
class phone-number implements Rule
{
```
**after:**
```
php artisan module:make-rule phone-number Test
namespace Modules\Test\Rules;
use Illuminate\Contracts\Validation\Rule;
class PhoneNumber implements Rule
{
```

fix class name when special characters are used the rule name

---

config/config.php

The two component creation commands have been forgotten in the modules file. 
#1188

Command "module:make-component" is not defined

---

src/Commands/ModelMakeCommand.php
tests/Commands/ModelMakeCommandTest.php
tests/Commands/__snapshots__/ModelMakeCommandTest__it_generates_controller_and_migration_when_both_flags_are_present__1.php
tests/Commands/__snapshots__/ModelMakeCommandTest__it_generates_controller_and_migration_when_both_flags_are_present__2.php
tests/Commands/__snapshots__/ModelMakeCommandTest__it_generates_controller_file_with_model__1.php
tests/Commands/__snapshots__/ModelMakeCommandTest__it_generates_controller_file_with_model_using_shortcut_option__1.php

Use controller flag to create and assign controller to a model
```
php artisan module:make-model User -c
```
result
```
Created : .../Modules/ModuleName/Entities/User.php
Created : .../Modules/ModuleName/Http/Controllers/UserController.php
```
or
```
php artisan module:make-model User -mc
```
result
```
Created : .../Modules/ModuleName/Entities/User.php
Created : .../Modules/ModuleName/Database/Migrations/2021_07_28_140048_create_users_table.php
Created : .../Modules/ModuleName/Http/Controllers/UserController.php
```
Note: There was also a [related pull request](https://github.com/nWidart/laravel-modules/pull/1254) and i closed it because of mistakes i made.

Add optional controller flag to model generator command

---

src/Migrations/Migrator.php

Laravel team introduce anonymous migration in Laravel 8.37, which solves migration class name collision issue.
Currently, the `module:migrate` command runs normally with anonymous migration.
But, `migrate-rollback` & `migrate-reset` trigger `Class not found` error.
So, I propose this changes to fix that issue.

Fix error on anonymous migration class

---

config/config.php

`ComponentClassMakeCommand::class` and `ComponentViewMakeCommand::class` are already defined on line [146](https://github.com/nWidart/laravel-modules/pull/1356/commits/ad55a60c068fc25a8d8c418d2e921823ce411c11#diff-f55db4bc294bbb90108ccfcbdd11881f4707473ad9384b382e2a6b653e118471L146) and [147](https://github.com/nWidart/laravel-modules/pull/1356/commits/ad55a60c068fc25a8d8c418d2e921823ce411c11#diff-f55db4bc294bbb90108ccfcbdd11881f4707473ad9384b382e2a6b653e118471L147) respectively

remove duplicate define commands from config

---

src/Commands/stubs/migration/add.stub
src/Commands/stubs/migration/create.stub
src/Commands/stubs/migration/delete.stub
src/Commands/stubs/migration/drop.stub
src/Commands/stubs/migration/plain.stub

Add Anonymous migration class as default like in Laravel 9.0

Anonymous migration class

---

src/FileRepository.php

See #1420 for issue.
This PR addresses points 3., 4. and 5. in the reported issue.
> 3. Assuming that both `recursiveSearch`  and `exclude` use specific filenames, we do not check once at the beginning of the function if the file we are searching for is in the exclude list and return immediately - instead we recurse all directories and filter out such files which seems to me to be a waste of time. (If we use `glob` style filters, then it would still need to be done in the `RecursiveCallbackFilterIterator`.)
>
> 4. The callback gets the `scan.exclude` array on every iteration rather than once when the function is called. 
>
> 5. The `recursiveSearch` function is looping through every directory and then every file and getting the filename and comparing it to the wanted filename. It would be …

Improve FileRepository performance

---

src/Commands/ModelShowCommand.php
src/Providers/ConsoleServiceProvider.php

This PR introduces a new `module:model-show` command that displays information for a model. It combines information from the database alongside information from Eloquent to give you a complete overview of your model. this command exclusively changed to this package.
more info about this Command : [[9.x] Artisan model:show command #43156](https://github.com/laravel/framework/pull/43156)
only change `qualifyModel` method to find model name in `Entities` Folder.

[feat] add command show model to package

---

src/Commands/DisableCommand.php

Despite allowing to disable all modules at once, the command `artisan module:disable` returns an exception when it receive `null` in the `module` argument
This setting allows the command to be output after disabling all modules.

FIX - DisableCommand.php

---

src/Commands/ModelMakeCommand.php

**Use optional seeder or request flag to create and assign => seeder and request to a model on model generator command.**
`php artisan module:make-model User Blog -s`
result:
`Created :..../Modules/Blog/Entities/User.php`
`Created :..../Modules/Blog/Database/Seeders/UserSeederTableSeeder.php`
or
`php artisan module:make-model User Blog -r`
result
`Created :..../Modules/Blog/Entities/User.php`
`Created : ..../Modules/Blog/Http/Requests/UserRequest.php`
or
`php artisan module:make-model User Blog -mcsr`
result
`Created :..../Modules/Blog/Entities/User.php`
`Created : ..../Modules/Blog/Database/Migrations/2022_08_03_044606_create_users_table.php`
`Created : ...../Modules/Blog/Http/Controllers/UserrrController.php`
`Created :..../Modules/Blog/Database/Seeders/UserSeederTableSeeder.php` …

[feat] optional flag for seeder or request in model generator command

---

src/Commands/DisableCommand.php
src/Commands/GeneratorCommand.php
src/Commands/ListCommand.php
src/Commands/MiddlewareMakeCommand.php
src/Commands/MigrationMakeCommand.php
src/Commands/ModuleDeleteCommand.php
src/Commands/ModuleMakeCommand.php
src/Generators/ModuleGenerator.php
tests/Commands/ModuleMakeCommandTest.php

in this PR update commands to  new look for Artisan.
base of this PR is: [[9.x] Introducing a fresh new look for Artisan #43065](https://github.com/laravel/framework/pull/43065)
updated command list is : 
- `module:disable`
- `module:delete`
- `module:list`
- `module:make-middleware`
- `module:make-migration`
- `module:make`
Other commands will be updated soon...

[feat] update command style to new version of artisan

---

src/Commands/FactoryMakeCommand.php

When config `paths.generator.model.path` is set to `Eloquent/Models`, the Factory model generated from `make-factory` command will be like this
```
class UserFactory extends Factory
{
protected $model = \Modules\Core\Eloquent/Models/User::class;
// ...
}
```
When generating model namespace, it assumes only one layer for the folder.
```
public function getModelNamespace(): string
{
return $this->laravel['modules']->config('namespace') . '\\' . $this->laravel['modules']->findOrFail($this->getModuleName()) . '\\' . $this->laravel['modules']->config('paths.generator.model.path', 'Entities');
}
```
To replace `/` string with `\\` string in `$this->laravel['modules']->config('paths.generator.model.path', 'Entities')`

Fix make-factory command when model path is nested path

---

src/Commands/ModelShowCommand.php

Pull request to fix issue described in https://github.com/nWidart/laravel-modules/issues/1482

Use AsCommand in lieu of defaultName for ModelShowCommand

---

src/Commands/stubs/scaffold/provider.stub

The method [loadJsonTranslationsFrom](https://laravel.com/api/9.x/Illuminate/Support/ServiceProvider.html#method_loadJsonTranslationsFrom) doesn't want the namespace as second parameter, as is the case for [loadTranslationsFrom](https://laravel.com/api/9.x/Illuminate/Support/ServiceProvider.html#method_loadTranslationsFrom).
The documentation should also be reviewed

loadJsonTranslationsFrom doesn't have 2 parameters

---

CHANGELOG.md
composer.json
phpunit.xml.dist
src/Commands/ModelShowCommand.php
tests/BaseTestCase.php
tests/Commands/ComponentClassMakeCommandTest.php
tests/Commands/ComponentViewMakeCommandTest.php
tests/LaravelModuleTest.php

Hi there,
I wasn't sure about how you'd handle bumping major version of a package & laravel, but I took a look at the commit for the previous major version bump to L9 and hopefully this PR helps to save some time.
Let me know if there's anything else that I can help out with.
Close #1521

Support for Laravel 10

---

config/config.php
src/Commands/ObserverMakeCommand.php
src/Commands/stubs/observer.stub
src/Providers/ConsoleServiceProvider.php
tests/BaseTestCase.php
tests/Commands/ObserverMakeCommandTest.php
tests/Commands/__snapshots__/ObserverMakeCommandTest__it_makes_observer__1.php
tests/Commands/__snapshots__/ObserverMakeCommandTest__it_makes_observer__1.txt

After merging this PR we can make a new observer based on the selected model, The related command to be run is:
```
php artisan module:make-observer Post Blog
```
This command will create `PostObserver` inside the `Moudles\Blog\Observers` directory and contain all necessary functions to be observed.

Add Make Observer Command

---

src/Commands/stubs/rule.stub
tests/Commands/__snapshots__/ControllerMakeCommandTest__it_generates_an_api_controller__1.txt
tests/Commands/__snapshots__/ModuleMakeCommandTest__it_generates_api_module_with_resources__2.txt
tests/Commands/__snapshots__/RuleMakeCommandTest__it_can_change_the_default_namespace__1.txt
tests/Commands/__snapshots__/RuleMakeCommandTest__it_can_change_the_default_namespace_specific__1.txt
tests/Commands/__snapshots__/RuleMakeCommandTest__it_makes_rule__1.txt

This PR ships new rule stub because `Illuminate\Contracts\Validation\Rule` has been deprecated in Laravel 10.
https://github.com/laravel/framework/pull/45954

New rule stub

---

src/Commands/stubs/request.stub

Removed the commented code sample. `// return auth()->user()->can('users.create');`
In response to the issue #1684

Removed the commented code sample. `// return auth()->user()->can('users.create');`

---

src/Commands/ModelShowCommand.php

Hi,
In #1699, the class extension was modified, but it's not correct.
In the attached screenshot, the namespace is `Illuminate\Foundation\Console\ShowModelCommand`, but the correct namespace is `Illuminate\Database\Console\ShowModelCommand` and exist [file_url](https://github.com/laravel/framework/blob/88d6037dcda4f5696b85ce24ad11ff7e97fd14f0/src/Illuminate/Database/Console/ShowModelCommand.php
)
I believe his package has not been updated to the latest version, but the Laravel version has been updated.
This command is based on a Laravel command. The only change made is in the method `qualifyModel` to locate the Model from the modules folder. For more information, please refer to #1429.

[fix] revert extend class to ShowModelCommand

---

config/config.php

Hi,
In the last PR (#1720), a section except was added, but it is not functioning as intended. This is because it deletes keys. Based on @dcblogdev's suggestion, it is recommended to drop it.

[feat] delete except section

---

composer.json
src/Commands/ModelPruneCommand.php
src/Providers/ConsoleServiceProvider.php

Hi,
In this PR, a new command `module:prune` is added to this package. This command extends from the base `module:prune` and only modifies the method `models` to find Prunable models from modules. Additionally, some arguments are added to the command.
The usage of this command is as follows:
1. When calling the command without arguments, it shows a multiselect prompt in Laravel, allowing you to choose which module to check. You can also choose the 'All' option to check all modules.
```sh
php artisan module:prune
```
2. To check all modules, use the `--all` option when running the command.
```sh
php artisan module:prune --all
```
3. Pass the module name as an argument:
```sh
php artisan module:prune Base Cloud
```
Additionally, the Laravel/framework version is updated in this PR.
If you …

Add command module prune

---

src/Commands/BaseCommand.php
src/Commands/CheckLangCommand.php
src/Commands/DisableCommand.php
src/Commands/DumpCommand.php
src/Commands/EnableCommand.php
src/Commands/MigrateCommand.php
src/Commands/MigrateRefreshCommand.php
src/Commands/MigrateResetCommand.php
src/Commands/MigrateRollbackCommand.php
src/Commands/MigrateStatusCommand.php
src/Commands/ModuleDeleteCommand.php
src/Commands/PublishCommand.php
src/Commands/PublishConfigurationCommand.php
src/Commands/PublishMigrationCommand.php
src/Commands/PublishTranslationCommand.php
src/Commands/SeedCommand.php
src/Commands/UnUseCommand.php
src/Commands/UpdateCommand.php
src/Commands/UseCommand.php
tests/Commands/DisableCommandTest.php
tests/Commands/EnableCommandTest.php

Hi,
In this pull request, I've begun refactoring the structure of the command. The rules for all commands are as follows:
1. When called without any arguments, it will show a multiselect of Laravel prompts to choose which module should be checked.
2. When the option `--all` is passed, it will check all modules.
3. Module names can be passed as arguments to the command.
Example:
```sh
php artisan module:use
```
---
```sh
php artisan module:use --all
```
---
```sh
php artisan module:use base wallet
```
In this PR, I've updated the following commands:

Implement base command

---

src/Commands/CheckLangCommand.php

Additionally fixes the hardcoded path to "Resources/lang"

Fix Issue #1752 - Hardcoded string + undefined variable

---

src/Module.php

This provides a fix for issue #1731 .
Uses a similar bit of code to what has been proposed only with the if statement being flipped. Prior to this fix, I was getting the following console errors.

fix: Failed to load module script for static assets such as images

---

config/config.php

Hi,
This fix ensures the automatic creation of the migration folder when generating a new module, enhancing project organization and developer convenience.

[fix] enable create folder of migration on make new module

---

src/Module.php

Hi,
I've added a method `getAppPath` to return the app path of each module. If the app directory does not exist, the results of `getPath` and `getAppPath` will be the same.

[feat] add method 'getAppPath'

---

config/config.php
src/Commands/Make/ModuleMakeCommand.php
src/Generators/ModuleGenerator.php
tests/Commands/ModuleMakeCommandTest.php
tests/Commands/__snapshots__/ModuleMakeCommandTest__test_it_generate_module_when_provider_is_enable_and_route_provider_is_disable__1.txt
tests/Commands/__snapshots__/ModuleMakeCommandTest__test_it_generate_module_when_provider_is_enable_and_route_provider_is_enable__1.txt
tests/Commands/__snapshots__/ModuleMakeCommandTest__test_it_generate_module_when_provider_is_enable_and_route_provider_is_enable__2.txt

Hi,
This pull request fix issue #1779 by adding configuration for RouteServiceProvider in the generator.
Additionally, when the provider is disabled, it removes the namespace from `module.json`. Furthermore, if the route provider is disabled, it comments out the registration of RouteServiceProvider in the ServiceProvider as follows:
```php
/**
* Register the service provider.
*/
public function register(): void
{
// $this->app->register(RouteServiceProvider::class);
}
```
These changes aim to improve the configuration and flexibility of the generator.

Add RouteServiceProvider Configuration in Generator

---

src/Commands/Make/ModuleMakeCommand.php
src/Generators/ModuleGenerator.php

Example of usage:
--author-name=value
--author-email=value
--author-vendor=value
All values are optional.
`php artisan module:make --author-name=Alex`
It is useful for modular development to avoid being tied to the system configuration.

Passing the values of vendor, author's name, and author's email in a line during module creation.

---

README.md

Hi,
In this pull request, I've added an `Upgrade Guide` section to the README of the module. 
@dcblogdev Additionally, I propose adding the URL of this upgrade guide to the release notes of [v11.0.0](https://github.com/nWidart/laravel-modules/releases/tag/v11.0.0). 
Many users have encountered issues recently, such as providers not working, and it's likely because they haven't consulted the upgrade guide. You can find related discussions in the following issues:
- [#1805](https://github.com/nWidart/laravel-modules/issues/1805)
- [#1797](https://github.com/nWidart/laravel-modules/issues/1797)
- [#1781](https://github.com/nWidart/laravel-modules/issues/1781)
- [#1795](https://github.com/nWidart/laravel-modules/issues/1795)

Add Upgrade Guide Section to README

---

src/Commands/BaseCommand.php

hi,
if command has option 'direction', load module list with 'priority'.
fix #1816

[fix] check command has direction option, load module with 'priority'

---

config/config.php
src/Commands/Make/ServiceMakeCommand.php
src/Commands/stubs/service.stub
src/Providers/ConsoleServiceProvider.php
tests/Commands/ServiceMakeCommandTest.php
tests/Commands/__snapshots__/ServiceMakeCommandTest__test_it_can_change_the_default_namespace__1.txt
tests/Commands/__snapshots__/ServiceMakeCommandTest__test_it_can_generate_a_service_in_sub_namespace_with_correct_generated_file__1.txt
tests/Commands/__snapshots__/ServiceMakeCommandTest__test_it_generated_correct_file_with_content__1.txt

This PR adds the ability to generate service classes using `php artisan module:make-service ServiceName ModuleName`
Added service generator
Added Tests
Added Stub
This does require the application config file to add a service to the generator paths:
```php
'service' => ['path' => 'app/Services', 'generate' => false],
```

added make-service class

---

src/Module.php

The path to `build/manifest.json` is relative, which works if the executing PHP file is in the public folder. If you use Laravel Octane the executing script is the `artisan` script which is in the working directory, and so the paths are incorrect.
I fixed this by using the `public_path` function.

Fixed public path for octane setup

---

src/Commands/Database/SeedCommand.php

Hi, in this PR, I added the `direction` option to the `module:seed` command.
Fixes #1833.

[feat] add `direction` option to command `module:seed`

---

src/Commands/stubs/helper-invoke.stub
src/Commands/stubs/helper.stub
tests/Commands/__snapshots__/ActionMakeCommandTest__test_it_can_generate_a_action_in_sub_namespace_with_correct_generated_file__1.txt
tests/Commands/__snapshots__/ActionMakeCommandTest__test_it_generated_correct_file_with_content__1.txt
tests/Commands/__snapshots__/ControllerMakeCommandTest__test_it_generates_an_invokable_controller__1.txt
tests/Commands/__snapshots__/HelperMakeCommandTest__test_it_can_generate_a_helper_in_sub_namespace_with_correct_generated_file__1.txt
tests/Commands/__snapshots__/HelperMakeCommandTest__test_it_generated_correct_file_with_content__1.txt
tests/Commands/__snapshots__/ServiceMakeCommandTest__test_it_can_generate_a_service_in_sub_namespace_with_correct_generated_file__1.txt
tests/Commands/__snapshots__/ServiceMakeCommandTest__test_it_generated_correct_file_with_content__1.txt

This commit replaces the `__construct()` method in generated controller, service, helper, and action classes with `handle()`. 
Also, it changes `__invokable()` in the helper-invoke.stub to `__invoke()`. This makes them more immediately useful for handling requests or other actions.

Update controller, service, helper, and action methods

---

src/Commands/Actions/ModuleDeleteCommand.php
src/Commands/BaseCommand.php
src/Contracts/ConfirmableCommand.php
tests/Commands/ModuleDeleteCommandTest.php

Hi,
In this pull request, I have added an option for confirmation before executing certain commands. Previously, the delete command ran without confirmation, which could lead to accidental and irreversible data loss.
I have also added an option to pass `--force` to delete without confirmation, allowing for the previous behavior when needed.
```sh
php artisan module:delete Foo --force
```
This change addresses issue #1859.
Thank you for reviewing this pull request.

Add Confirmation Option for Command Execution

---

src/Commands/Database/MigrateCommand.php
src/Commands/Database/MigrateFreshCommand.php

Hi,
This pull request contains two main changes.
---
I moved the functionality of the `module:migrate-fresh` command to a new structure and extended it from `baseCommand` to allow selecting a specific module for migration.
Additionally, I refactored the `module:migrate-fresh` command to handle the fresh migration process manually with the following steps:
1. Drop all tables.
2. Create the migration table.
3. Check and run the root migrations (excluding the Modules folder).
4. Execute the `module:migrate` command for the selected module.
---
The previous functionality did not run migrations from subfolders in the `database/migrations` directory. Sometimes, custom folders are defined for migrations within a module to manage different versions or conditions, such as:
```php …
```

Refactor and Improve `module:migrate` and `module:migrate:fresh` Commands

---

src/Json.php

Hi,
In this pull request, I propose removing the cached JSON file reading and instead reading directly from the file. This approach is significantly faster (~12x on my OS).
> Before merging, please test this on your own system.
1. **Create a new fresh Laravel project and generate 150 modules.** Use the following console command:
```php
use Illuminate\Support\Facades\Artisan;
Artisan::command('create', function () {
$module_names = collect(range(0, 150))
->map(function ($item) {
return 'module' . $item;
})
->toArray();
\Illuminate\Support\Facades\Artisan::call('module:make', [
'name' => $module_names,
]);
});
```
Run this command in the terminal:
```sh
php artisan create
```
2. **Publish the module config file and set `cache.enabled` to true** or set the environment variable …

Improvement: Remove Cached JSON File Reading for Faster Performance

---

src/Constants/ModuleEvent.php
src/FileRepository.php
src/Generators/ModuleGenerator.php
src/Module.php
tests/Commands/Actions/ModuleDeleteCommandTest.php
tests/Commands/Make/ModuleMakeCommandTest.php
tests/LaravelFileRepositoryTest.php
tests/LaravelModuleTest.php
tests/LumenModuleTest.php

Hi,
In this pull request, I have added events for various actions and created a constant `ModuleEvent` to manage event names.
- New events added: `creating`, `created`, `deleting`, `deleted`, `used`, `unused`
- Existing events updated for usage: `boot`, `register`, `disabling`, `disabled`, `enabling`, `enabled`
This pull request depends on #1879, as provider files are registered with a single file. It's important to add a listener to clear the manifest file after certain actions.
Thanks.

Add Event Handling and Constants for Module Actions

---

src/Commands/BaseCommand.php

Hi,
In this pull request, I have changed `multiselect` to `multisearch` in the Laravel prompt. This modification allows for faster searching and selection of modules, which is especially useful when the module list is loaded with priority, such as in the migrate command.
This improvement enhances the efficiency of managing projects with many modules.
Thanks.

Change `Multiselect` to `Multisearch` in BaseCommand

---

composer.json

#1872 introduced Laravel pint but incorrectly marked it a dependency instead of as a dev-dependency. 
The result of this is that Laravel pint gets installed in production

Lavavel Pint as a dev-dependency

---

src/Commands/Database/MigrateFreshCommand.php

Hi,
While testing the `module:migrate-fresh` command, I discovered that root migrations were not being executed before the module migrations.
This issue occurs because, in the Laravel framework's `migrate` command, the default migration paths are merged when the method is called, but they are not registered by default. You can see the relevant code here: [Laravel Framework Migration Command](https://github.com/laravel/framework/blob/6ce800fdafdb0ed17ae62c65a78f8ced9b10003d/src/Illuminate/Database/Console/Migrations/BaseCommand.php#L27-L29).
```php
return array_merge(
$this->migrator->paths(), [$this->getMigrationPath()]
);
```
This pull request addresses and fixes this issue, ensuring that root migrations are executed before module migrations.

Fix for Running Root Migrations Before Module Migrations

---

src/Contracts/RepositoryInterface.php
src/FileRepository.php
src/Generators/ModuleGenerator.php
src/Json.php
src/Traits/CanClearModulesCache.php
tests/Commands/Actions/ModuleDeleteCommandTest.php

Hi,
In this pull request, I've updated the logic of the `FileRepository` to significantly speed up the load time of modules by storing the result of the `scan` method in a static variable.
To test this improvement, I created 166 modules and benchmarked the `isEnabled()` method of the package.
**Benchmark Code:**
```php
$modules = [
"A1"        => "A1",
"A2"        => "A2",
"Ali"       => "Ali",
"Auth"      => "Auth",
"Module0"   => "Module0",
"Module1"   => "Module1",
"Module10"  => "Module10",
// other modules name
"Module98"  => "Module98",
"Module99"  => "Module99",
"Profile"   => "Profile",
];
\Illuminate\Support\Benchmark::dd([
'check1' => function () use ($modules) {
$module = array_rand($modules);
$a      = \Nwidart\Modules\Facades\Module::isEnabled($module);
},
], 30);
``` …

Blazing Fast Module Loading 🚀😎

---

.github/ISSUE_TEMPLATE/1_Bug_report.md
.github/ISSUE_TEMPLATE/2_Feature_request.md
.github/ISSUE_TEMPLATE/config.yml

Hi,
This pull request adds an issue template that prompts users to provide the Laravel and package version before creating an issue. This aims to improve the response process by ensuring that essential information is available from the start.
Here’s a preview:
Thanks!

Add Issue Template for Improved Support

---

config/config.php
src/Activators/FileActivator.php
src/Module.php
src/Traits/CanClearModulesCache.php

Hi,
In this pull request, I've removed the caching mechanism for the `module_status.json` file and switched to reading it directly. The direct read operation is fast and not need cache.
Additionally, I've completely removed the cache-related code from the package and cleaned up unused keys in the config file.

Delete cache of module_status.json

---

src/ModuleManifest.php
src/ModulesServiceProvider.php

Hi,
In this pull request, I fixed the issue with loading files defined in `module.json`. After changing the registration of providers with a single file, the files were not being loaded correctly.
This pull request resolves #1942.

[feat] handle load files of module

---

scripts/vite-module-loader.js

Fix for https://github.com/nWidart/laravel-modules/issues/1867   
currently, vite-module-loader.js is  not working correctly  on Windows os
this enables compatibility with Linux and Windows to load the vite.config for all modules

Update vite-module-loader.js to load vite.config for all modules on windows 

---

src/Commands/stubs/scaffold/provider.stub
tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generate_module_when_provider_is_enable_and_route_provider_is_disable__1.txt
tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generate_module_when_provider_is_enable_and_route_provider_is_enable__1.txt
tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generates_api_module_with_resources__1.txt
tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generates_module_namespace_using_studly_case__1.txt
tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generates_module_resources__1.txt
tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generates_web_module_with_resources__1.txt
tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generates_web_module_with_resources_when_adding_more_than_one_option__1.txt
tests/Commands/Make/__snapshots__/ProviderMakeCommandTest__test_it_can_change_the_default_namespace__1.txt
tests/Commands/Make/__snapshots__/ProviderMakeCommandTest__test_it_can_change_the_default_namespace_specific__1.txt
tests/Commands/Make/__snapshots__/ProviderMakeCommandTest__test_it_can_have_custom_migration_resources_location_paths__1.txt
tests/Commands/Make/__snapshots__/ProviderMakeCommandTest__test_it_generates_a_master_service_provider_with_resource_loading__1.txt

This PR ads support for multiple root level config files but also nested folders.
for example
```
config/
admin/admin.php
admin.php
config.php
user.php
```
Then to use them `config('module.file.name')` for example `config('books.service.name')` to load `config/service.php` from a module called `Books`
Usage of the default config.php is unchanged. ie `config('module.name')` will load the name key from `module/config/config.php`

add support for multiple config files and nested config files

---

src/Generators/ModuleGenerator.php

Hi,
In this pull request, I address an issue that occurs when creating a new module (not the first module). Since the list of modules is stored in a static variable during execution, the newly created module’s files are not immediately recognized. This creates problems when subsequent commands are called, such as:
- module:make-seed
- module:make-event-provider
- module:route-provider
- module:make-controller
To resolve this, I reset the static variable used for storing the module list. This ensures the module paths are re-scanned, allowing the new module to be fully recognized and enabling the commands to work correctly.
Fixes #1956

Reset Static Variable for Module Creation

---

composer.json
src/Commands/Actions/ModelShowCommand.php

Hi,  
This pull request updates the `module:model-show` command to align its functionality with the `model:show` command of the Laravel framework. For additional details, you can refer to the related [Laravel Framework Pull Request](https://github.com/laravel/framework/pull/53541).  
The `qualifyModel` method has been removed from the framework. I have implemented the `promptForMissingArgumentsUsing` method from Laravel's console prompt system to handle model resolution interactively.  
fixes #1989.

Synchronize `module:model-show` Command with `model:show` Command in Laravel Framework

---

src/Commands/Actions/ModuleDeleteCommand.php
src/Commands/BaseCommand.php
src/Commands/Database/MigrateFreshCommand.php
src/Commands/Database/MigrateRefreshCommand.php
src/Commands/Database/MigrateResetCommand.php
src/Facades/Module.php

Hi,
In this pull request, I’ve added a `prohibitDestructiveCommands` method to the Module facade. This method allows you to indicate whether destructive Artisan commands should be prohibited, especially in production environments.
The commands affected are:
- `module:migrate-fresh`  
- `module:migrate-refresh`  
- `module:migrate-reset`  
To enable this feature, add the following line to your service provider:
```php
Module::prohibitDestructiveCommands($this->app->isProduction());
```
This ensures that these potentially harmful commands are disabled when running in a production environment, adding an extra layer of safety for your application.
Additionally, this PR updates the confirmable messages to provide clearer communication to users when running these commands.
Thanks.

Add `prohibitDestructiveCommands` Method to Prevent Running Destructive Commands in Production

---

config/config.php
src/Commands/Make/RouteProviderMakeCommand.php
src/Generators/ModuleGenerator.php
src/Module.php

This PR adds support to use kebab case for routes.
To enable this edit your config file and change the path location to your local stub files (publish them if you don't have them)
```php
'stubs' => [
'enabled' => false,
'path' => base_path('stubs/nwidart-stubs'),
```
Also add KEBAB in the replacements array:
```php
'replacements' => [
'routes/web' => ['LOWER_NAME', 'KEBAB_NAME', 'STUDLY_NAME', 'MODULE_NAMESPACE', 'CONTROLLER_NAMESPACE'],
'routes/api' => ['LOWER_NAME', 'STUDLY_NAME', 'MODULE_NAMESPACE', 'CONTROLLER_NAMESPACE'],
```
Then to use in your routes stub edit /stubs/nwidart-stubs/web.stub
```php
Route::group([], function () {
Route::resource('$KEBAB_NAME$', $STUDLY_NAME$Controller::class)->names('$KEBAB_NAME$');
});
```
Next time a module is created it will use the KEBAB case.

added option to use kebab case

---

src/Commands/ModuleClearCompiledCommand.php
src/Commands/ModuleDiscoverCommand.php
src/ModuleManifest.php
src/ModulesServiceProvider.php
tests/Commands/Actions/ClearCompiledCommandTest.php
tests/Commands/Actions/ModuleDiscoverCommandTest.php

Hi,  
In this pull request, I have removed the caching of provider data in the `bootstrap/cache/module.php` file. Storing this cache causes several issues:  
1. Changes in `module_status.json` are not detected until `module:discover` or `module:delete-compile` is executed.  
2. When copying a module directly into the `Modules` folder, Laravel does not detect it until the command is run.  
3. Switching between branches with different module statuses leads to inconsistencies (#2020).  
Since this file is only used once during Laravel's booting process, we can safely remove its caching mechanism.  
Additionally, this pull request updates the messages for `module:discover` and `module:delete-compile`, clarifying their removal in the next major version. Tests related to these commands have …

Remove Cached Module Providers Manifest to Improve Dynamic Module Detection  

---

src/Commands/Make/ModelMakeCommand.php

add flags 'all', 'resource', and 'policy'
All options:
```bash
-a, --all                  Flag to create all associated files
-c, --controller           Flag to create associated controllers
--fillable[=FILLABLE]  The fillable attributes.
-f, --factory              Create a new factory for the model
-m, --migration            Flag to create associated migrations
-r, --request              Create a new request for the model
-R, --resource             Create a new resource for the model
-p, --policy               Create a new policy for the model
-s, --seed                 Create a new seeder for the model
```

Make model with flags

---

config/config.php
src/Generators/ModuleGenerator.php

Hi,  
This pull request adds support for **closures in stub variable replacements**, allowing dynamic values to be set in published configuration files.  
In the `module.php` file, under the `stubs/replacements` section, you can now define variables as closures:  
```php
'composer' => [
'CUSTOM_KEY' => fn (\Nwidart\Modules\Generators\ModuleGenerator $generator) => $generator->getName() . '-module',
'CUSTOM_KEY1' => fn () => 'custom text',
'LOWER_NAME',
'STUDLY_NAME',
'VENDOR',
'AUTHOR_NAME',
'AUTHOR_EMAIL',
'MODULE_NAMESPACE',
'PROVIDER_NAMESPACE',
'APP_FOLDER_NAME',
],
```
In stub files, use the defined variables as placeholders:  
```json
{
"name": "$VENDOR$/$LOWER_NAME$",
"description": "$CUSTOM_KEY$ $CUSTOM_KEY1$",
"authors": [
{
"name": "$AUTHOR_NAME$",
"email": "$AUTHOR_EMAIL$"
}
] …
```

Add Support for Closures in Stub Variable Replacement

---

src/LaravelModulesServiceProvider.php
src/helpers.php
tests/ModuleHelperTest.php

> Module status
```php
$status = module('blog');
```
```php
if (module('blog')) {
return "Blogs";
}
```
> Module instance
```php
$blog = module('blog', true);
```
> Blade directive
```blade
@module('blog')
<h3> Blogs </h3>
@endmodule
```
```blade
@module('blog')
<h3> Blogs </h3>
@else
<p> No Blogs </p>
@endmodule
```

Create `module()` helper function and `@module()` blade directive

---

src/Commands/stubs/scaffold/provider.stub
tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generate_module_when_provider_is_enable_and_route_provider_is_disable__1.txt
tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generate_module_when_provider_is_enable_and_route_provider_is_enable__1.txt
tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generates_api_module_with_resources__1.txt
tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generates_module_namespace_using_studly_case__1.txt
tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generates_module_resources__1.txt
tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generates_web_module_with_resources__1.txt
tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generates_web_module_with_resources_when_adding_more_than_one_option__1.txt
tests/Commands/Make/__snapshots__/ProviderMakeCommandTest__test_it_can_change_the_default_namespace__1.txt
tests/Commands/Make/__snapshots__/ProviderMakeCommandTest__test_it_can_change_the_default_namespace_specific__1.txt
tests/Commands/Make/__snapshots__/ProviderMakeCommandTest__test_it_can_have_custom_migration_resources_location_paths__1.txt
tests/Commands/Make/__snapshots__/ProviderMakeCommandTest__test_it_generates_a_master_service_provider_with_resource_loading__1.txt

This PR improves the configuration merging logic within module service providers by eliminating adjacent duplicate segments in config keys. This ensures cleaner and more predictable keys, such as `tenancy.tenant_model` instead of `tenancy.tenancy.tenant_model`.
- Updated `registerConfig()` to normalize config keys by removing consecutive duplicate segments.
- Prevents redundant nesting like `tenancy.tenancy`.
- Helps avoid configuration resolution issues in packages expecting standard key formats.
**Before:**
```php
$this->nameLower = 'tenancy'
$relativePath = 'tenancy.php'
Merged key => tenancy.tenancy
Resolved: config('tenancy.tenancy.tenant_model')
```
**After:**
```php
$this->nameLower = 'tenancy'
$relativePath = 'tenancy.php'
Normalized key => tenancy
Resolved: …
```

Enhance Config Merging Logic to Prevent Duplicate Keys in Modules

---

src/Commands/stubs/scaffold/provider.stub
tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generate_module_when_provider_is_enable_and_route_provider_is_disable__1.txt
tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generate_module_when_provider_is_enable_and_route_provider_is_enable__1.txt
tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generates_api_module_with_resources__1.txt
tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generates_module_namespace_using_studly_case__1.txt
tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generates_module_resources__1.txt
tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generates_web_module_with_resources__1.txt
tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generates_web_module_with_resources_when_adding_more_than_one_option__1.txt
tests/Commands/Make/__snapshots__/ProviderMakeCommandTest__test_it_can_change_the_default_namespace__1.txt
tests/Commands/Make/__snapshots__/ProviderMakeCommandTest__test_it_can_change_the_default_namespace_specific__1.txt
tests/Commands/Make/__snapshots__/ProviderMakeCommandTest__test_it_can_have_custom_migration_resources_location_paths__1.txt
tests/Commands/Make/__snapshots__/ProviderMakeCommandTest__test_it_generates_a_master_service_provider_with_resource_loading__1.txt

Fixed path for class based components replaces
```php
$componentNamespace = str_replace('/', '\\', config('modules.namespace').'\\'.$this->moduleName.'\\'.config('modules.paths.generator.component-class.path'));
Blade::componentNamespace($componentNamespace, $this->moduleNameLower);
```
with
```php
Blade::componentNamespace(config('modules.namespace').'\\' . $this->moduleName . '\\View\\Components', $this->moduleNameLower);
```

fix: update component namespace generation in module make command tests

---

src/Commands/stubs/scaffold/provider.stub
tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generate_module_when_provider_is_enable_and_route_provider_is_disable__1.txt
tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generate_module_when_provider_is_enable_and_route_provider_is_enable__1.txt
tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generates_api_module_with_resources__1.txt
tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generates_module_namespace_using_studly_case__1.txt
tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generates_module_resources__1.txt
tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generates_web_module_with_resources__1.txt
tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generates_web_module_with_resources_when_adding_more_than_one_option__1.txt
tests/Commands/Make/__snapshots__/ProviderMakeCommandTest__test_it_can_change_the_default_namespace__1.txt
tests/Commands/Make/__snapshots__/ProviderMakeCommandTest__test_it_can_change_the_default_namespace_specific__1.txt
tests/Commands/Make/__snapshots__/ProviderMakeCommandTest__test_it_can_have_custom_migration_resources_location_paths__1.txt
tests/Commands/Make/__snapshots__/ProviderMakeCommandTest__test_it_generates_a_master_service_provider_with_resource_loading__1.txt

This PR introduces a core enhancement to the `registerConfig()` logic. It ensures that configuration files within a module (e.g., `modules/Blog/config/config.php` or `modules/Blog/config/blog.php`) override Laravel's root application configs (e.g., `config/blog.php`) during registration.
The modular architecture encourages encapsulation of logic and behavior per domain (module). However, Laravel’s default `mergeConfigFrom()` merges shallowly and always prioritizes existing config values, meaning module-defined values are ignored if a root config already exists.
This directly contradicts the core idea of modularity - that a module should define and control its behavior without being limited by app-level configs.
By allowing module configs to override root configs, developers get:
- …

Allow Module Configs to Override Root Application Configs

---

src/Lumen/LumenFileRepository.php

The class `Nwidart\Modules\Module` is abstract and cannot be instantiated directly.
The correct class to use in a Lumen is `Nwidart\Modules\Lumen\Module`, which extends `Nwidart\Modules\Module`.

[fix] fix Error Cannot instantiate abstract class

---

src/helpers.php
tests/ModuleHelperTest.php

This pull request includes several improvements and cleanups to the `module` helper:
* Refactored variable names for better readability and consistency
* Updated return type from `Nwidart\Modules\Laravel\Module` to the more generic `Nwidart\Modules\Module` to support both Laravel and Lumen. (in helper and tests)
* Removed unnecessary `Log::error` call
* Added handling for `ModuleNotFoundException` when calling the `isEnabled()` method

Refactor `module` helper, improve code clarity, and handle exceptions

---

src/Commands/Actions/ListCommands.php
src/Providers/ConsoleServiceProvider.php
tests/Commands/Actions/ListCommandsTest.php

add a new command `module:list-commands` this will scan your active modules and show a list of all found commands
```
┌ Select Modules ──────────────────────────────────────────────┐
│ All                                                          │
└──────────────────────────────────────────────────────────────┘
INFO  Listing commands...  
Billing/Console ........................................................................................................  
SUCCESS  app:collect-upcoming-orders-payments.  
Marketing/Console ......................................................................................................  
SUCCESS  marketing:send-historical-orders-to-klaviyo.  
SUCCESS  marketing:send-product-review-notifications-command.  
SUCCESS …
```

Add ListCommands Command

---

src/FileRepository.php
src/LaravelModulesServiceProvider.php

Moved module registration to the `register()` method to ensure that module service providers are loaded early and take their proper place in the Laravel lifecycle. Previously, module service providers were being registered during the `boot()` phase, which caused their `register()` methods to run too late — during the boot stage — leading to incorrect and unintended behavior.
Additionally, removed the cacheManager dependency from the FileRepository, as it is not available in the `register()` phase and was not being used.

Ensure modules are registered in register phase

---

src/Support/Migrations/NameParser.php

Hi,
This pull request fixes #2096.
The `getTableName` method’s return type can be null, so its type declaration has been updated.

[fix] fix return type of method
