- src/Module.php
- tests/RepositoryTest.php
In the project I work on we have some additional organization applied to our modules, which would be more elegant to work with if we could macro into the modules themselves some awareness of that structure. The Macroable trait is a simple solution to that problem.
> Add Macroable trait to Module

- src/Commands/DisableCommand.php
- src/Commands/DumpCommand.php
- src/Commands/EnableCommand.php
- src/Commands/GenerateListenerCommand.php
- src/Commands/InstallCommand.php
- src/Commands/ListCommand.php
- src/Commands/MakeCommand.php
- src/Commands/MigrateCommand.php
- src/Commands/MigrateRefreshCommand.php
- src/Commands/MigrateResetCommand.php
- src/Commands/MigrateRollbackCommand.php
- src/Commands/PublishCommand.php
- src/Commands/PublishConfigurationCommand.php
- src/Commands/PublishMigrationCommand.php
- src/Commands/PublishTranslationCommand.php
- src/Commands/SeedCommand.php
- src/Commands/SetupCommand.php
- src/Commands/UpdateCommand.php
- src/Commands/UseCommand.php
- src/Contracts/RunableInterface.php
- src/Generators/FileGenerator.php
- src/Generators/ModuleGenerator.php
- src/Migrations/Migrator.php
- src/Module.php
- src/Process/Installer.php
- src/Support/Migrations/SchemaParser.php
- tests/RepositoryTest.php
I did a quick pass on a set of inspection results, mostly cleaning up places where a return value was documented but never actually happened, etc. I didn't try to be super thorough, just trimming down some of the low-hanging fruit that IDEs like PHPStorm will complain about.
> Minor inspection cleanup

- src/Commands/stubs/scaffold/provider.stub
This won't break functionality if the folder structure of laravel was changed and the resource path was set correctly.
> Change base_path('resources/...') to resource_path('...')

- src/Process/Installer.php
1/ Add specific support for "gitlab" repo type during install
2/ Add support for generic git repo type during install
> Add support for generic git host

- src/Process/Updater.php
if require || require-dev is empty, composer ask to enter a package:
```
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Search for a package:
```
> hotfix install packages if exist

- src/Module.php
- src/Repository.php
Original from https://github.com/nWidart/laravel-modules/pull/277 and revert of https://github.com/nWidart/laravel-modules/commit/c7bad606db27fc67ad44d67f7d066fd8d25e18e0
> Lumen support ( change the docblocks )

- src/Laravel/Module.php
- src/Laravel/Repository.php
- src/LaravelModulesServiceProvider.php
- src/Lumen/Module.php
- src/Lumen/Repository.php
- src/LumenModulesServiceProvider.php
- src/Module.php
- src/ModulesServiceProvider.php
- src/Repository.php
- tests/LaravelModuleTest.php
- tests/LumenModuleTest.php
- tests/RepositoryTest.php
Hello,
Lumen 5.5.x was introduced and in order to make this module compatible with it needed to make few changes. Laravel and Lumen specific methods moved to separated classes.
> Lumen 5.5.x support

- config/config.php
- src/Commands/MakePolicyCommand.php
- src/Commands/stubs/policy.plain.stub
- src/Providers/ConsoleServiceProvider.php
- tests/BaseTestCase.php
- tests/Commands/MakePolicyCommandTest.php
Only creates stub with correct namespace and classname.
I changed how test look like, since I think its waste of time to test "if file is created" and then "check the contents". Let me make this clear, PR uses both assertions but in one test...
> Fix #344, introduce command for creating policies

- composer.json
- src/Laravel/Module.php
- src/Lumen/Module.php
- src/Module.php
- src/helpers.php
See https://github.com/nWidart/laravel-modules/pull/355
-  PR with the up to date upstream
-  Fixed class import of the AliasLoader
> Lumen 5.5.x support ( Removed mixed Laravel and Lumen dependencies )

- src/Commands/MigrateStatusCommand.php
- src/Providers/ConsoleServiceProvider.php
> Added migration status

- CHANGELOG.md
- README.md
- src/helpers.php
Added extra helper function and updated the readme
> Improved support for Lumen

- config/config.php
- src/Generators/ModuleGenerator.php
I'm aware what gitkeep files are for, yet I'd like to disable them. This PR adds an option to turn their generation off.
> Make gitkeep optional

- src/Collection.php
- src/Laravel/Repository.php
- src/Lumen/Repository.php
> Cache and vendor directory

- src/Commands/stubs/start.stub
Flag comments always have three lines, with every line being three characters shorter than the one before it.
> Made start.stub more Laravel-like.

- src/Commands/SeedCommand.php
Example:
`php artisan module:seed User --class=UserSeeder`
> fix module:seed --class

- config/config.php
- phpunit.xml.dist
- src/Commands/RouteProviderMakeCommand.php
- src/Commands/stubs/route-provider.stub
- src/Commands/stubs/routes.stub
- src/Commands/stubs/routes/api.stub
- src/Commands/stubs/routes/web.stub
- tests/Commands/ModuleMakeCommandTest.php
- tests/Commands/__snapshots__/ModuleMakeCommandTest__it_generates_api_route_file__1.php
- tests/Commands/__snapshots__/ModuleMakeCommandTest__it_generates_module_resources__4.php
- tests/Commands/__snapshots__/ModuleMakeCommandTest__it_generates_web_route_file__1.php
- tests/Commands/__snapshots__/RouteProviderMakeCommandTest__it_can_change_the_default_namespace__1.php
- tests/Commands/__snapshots__/RouteProviderMakeCommandTest__it_generated_correct_file_with_content__1.php
In Laravel 5.3+ in addition to web.php route file you also have api.php route file
> API routes

- src/Commands/ControllerMakeCommand.php
- src/Commands/stubs/controller-api.stub
- src/Commands/stubs/controller.stub
- tests/Commands/ControllerMakeCommandTest.php
- tests/Commands/__snapshots__/ControllerMakeCommandTest__it_appends_controller_to_class_name_if_not_present__1.php
- tests/Commands/__snapshots__/ControllerMakeCommandTest__it_can_change_the_default_namespace__1.php
- tests/Commands/__snapshots__/ControllerMakeCommandTest__it_generated_correct_file_with_content__1.php
- tests/Commands/__snapshots__/ControllerMakeCommandTest__it_generates_an_api_controller__1.php
- tests/Commands/__snapshots__/ModuleMakeCommandTest__it_generates_module_resources__2.php
Change controller stubs according to core laravel controller stubs
> Add --api option to module:make-controller

- src/Process/Installer.php
Rewrote process to tempate method
Also can you  cherry pick this commit to v4 also?
> little rewrite to template method (due to changes in symfony/process:4.2)

- src/Commands/ControllerMakeCommand.php
I need extend this class and override the method
> Need to override the method

- src/Commands/stubs/controller.stub
- tests/Commands/__snapshots__/ControllerMakeCommandTest__it_appends_controller_to_class_name_if_not_present__1.php
- tests/Commands/__snapshots__/ControllerMakeCommandTest__it_can_change_the_default_namespace__1.php
- tests/Commands/__snapshots__/ControllerMakeCommandTest__it_can_change_the_default_namespace_specific__1.php
- tests/Commands/__snapshots__/ControllerMakeCommandTest__it_can_generate_a_controller_in_sub_namespace_with_correct_generated_file__1.php
- tests/Commands/__snapshots__/ControllerMakeCommandTest__it_generated_correct_file_with_content__1.php
- tests/Commands/__snapshots__/ModuleMakeCommandTest__it_generates_module_resources__2.php
Hello, this PR is a fix for the return type of a normal controller's methods.
> Fix controller return type

- src/Commands/stubs/migration/create.stub
- tests/Commands/__snapshots__/MigrationMakeCommandTest__it_generates_correct_create_migration_file_content__1.php
- tests/Commands/__snapshots__/MigrationMakeCommandTest__it_generates_foreign_key_constraints__1.php
- tests/Commands/__snapshots__/ModelMakeCommandTest__it_generates_correct_migration_file_name_with_multiple_words_model__1.php
- tests/Commands/__snapshots__/ModelMakeCommandTest__it_generates_migration_file_with_model__1.php
- tests/Commands/__snapshots__/ModelMakeCommandTest__it_generates_migration_file_with_model_using_shortcut_option__1.php
Similar to [PR #1001](https://github.com/nWidart/laravel-modules/pull/1001)
> Change bigIncrements method to id

- src/Commands/MigrateRefreshCommand.php
> Refactor MigrateRefreshCommand

- .github/workflows/php.yml
- .travis.yml
- CHANGELOG.md
- README.md
- composer.json
- src/Commands/stubs/scaffold/provider.stub
- tests/Commands/__snapshots__/ModuleMakeCommandTest__it_generates_module_namespace_using_studly_case__1.php
- tests/Commands/__snapshots__/ModuleMakeCommandTest__it_generates_module_resources__1.php
- tests/Commands/__snapshots__/ProviderMakeCommandTest__it_can_change_the_default_namespace__1.php
- tests/Commands/__snapshots__/ProviderMakeCommandTest__it_can_change_the_default_namespace_specific__1.php
- tests/Commands/__snapshots__/ProviderMakeCommandTest__it_can_have_custom_migration_resources_location_paths__1.php
- tests/Commands/__snapshots__/ProviderMakeCommandTest__it_generates_a_master_service_provider_with_resource_loading__1.php
- Removing the factories registration to support laravel 8
> Laravel 8 support

- src/Commands/stubs/command.stub
- tests/Commands/__snapshots__/CommandMakeCommandTest__it_can_change_the_default_namespace__1.php
- tests/Commands/__snapshots__/CommandMakeCommandTest__it_can_change_the_default_namespace_specific__1.php
- tests/Commands/__snapshots__/CommandMakeCommandTest__it_generated_correct_file_with_content__1.php
- tests/Commands/__snapshots__/CommandMakeCommandTest__it_uses_set_command_name_in_class__1.php
- Updated command stub (changed property $name to $signature)
- Updated test snapshots
> Command signature patch

- src/Commands/ListCommand.php
- src/FileRepository.php
> Updated list command to use getPriority method and priority property

- config/config.php
Fixes an incorrectly placed configuration key `composer-output`
> fix: feat: Silent composer

- config/config.php
Laravel create components classes on app/View/Components
> Keep the same folder Stracture as Laravel

- src/ModulesServiceProvider.php
- src/Support/Stub.php
publish nwidart-stubs to base directory
> publish stubs

- src/LaravelModulesServiceProvider.php
- src/ModulesServiceProvider.php
> Merge config in register method

- src/Commands/stubs/package.stub
https://github.com/nWidart/laravel-modules/issues/1285
> Laravel mix v6 support

- src/Commands/MigrateFreshCommand.php
- src/Providers/ConsoleServiceProvider.php
> Add MigrateFreshCommand

- src/Commands/stubs/scaffold/provider.stub
load `[ISO 639-1 Code].json` translation files in module
> fixed #954 json translation files

- src/Commands/stubs/route-provider.stub
Improve maintainability of stub generated code.
> RouteProvider Use variable to hold $MODULE$

- composer.json
- src/Commands/DisableCommand.php
- src/Commands/DumpCommand.php
- src/Commands/EnableCommand.php
- src/Commands/PublishCommand.php
- src/Commands/PublishConfigurationCommand.php
- src/Commands/PublishMigrationCommand.php
- src/Commands/PublishTranslationCommand.php
- src/Commands/SetupCommand.php
- src/Commands/UnUseCommand.php
- src/Commands/UpdateCommand.php
- src/Publishing/Publisher.php
HI,👋🏻
i this PR unification of logic this command:
- module:disable
- module:enable
- module:update
- module:dump
and update messages style to new version:
- module:publish
- module:publish-config
- module:publish-migration
- module:publish-translation
- module:unuse
- module:setup
and also update laravel/framework version to support new style see [v9.21.0](https://github.com/laravel/framework/releases/tag/v9.21.0)
> Update command style

- src/Commands/stubs/scaffold/provider.stub
- remove the unused Factory import
- replace the `\Config::get` with `config` function
> refactor provider stub

- src/Commands/DisableCommand.php
this PR adds feature to accept array of modules instead of single module to disable
> [feat] update DisableCommand  to get list of modules

- tests/Commands/DisableCommandTest.php
this pr add test for disabling modules command
> [feat] implement test for disabling commands

- src/Commands/stubs/scaffold/provider.stub
Fix: Module Components Class not working issue.
> Update provider.stub (Fix: Module components class issue)

- src/Commands/RuleMakeCommand.php
- src/Commands/stubs/rule.implicit.stub
- tests/Commands/RuleMakeCommandTest.php
- tests/Commands/__snapshots__/RuleMakeCommandTest__it_makes_implicit_rule__1.txt
This PR ships the way to make implicit rule https://laravel.com/docs/10.x/validation#implicit-rules
> Implicit rule

- src/Commands/TestMakeCommand.php
vendor/symfony/console/Input/InputOption.php:85
> Fix for Symfony/Console

- src/LaravelModulesServiceProvider.php
Hi,
add package version to `php artisan about` command.
> [feat] add package version to command 'about'

- config/config.php
- src/Commands/stubs/composer.stub
- src/Generators/ModuleGenerator.php
fix #1821
update stubs composer.json to read app_folder_name from config on create new module
> [fix] fix stubs composer for app_folder

- src/Commands/Make/GeneratorCommand.php
- src/Generators/ModuleGenerator.php
- src/Support/Config/GeneratorPath.php
- src/Traits/PathNamespace.php
- tests/Commands/__snapshots__/ComponentClassMakeCommandTest__it_can_change_the_default_namespace__1.txt
- tests/Commands/__snapshots__/ComponentClassMakeCommandTest__test_it_can_change_the_default_namespace__1.txt
- tests/Commands/__snapshots__/TestMakeCommandTest__it_can_change_the_default_unit_namespace_specific__1.txt
- tests/Commands/__snapshots__/TestMakeCommandTest__it_generated_correct_feature_file_with_content__1.txt
- tests/Commands/__snapshots__/TestMakeCommandTest__it_generated_correct_unit_file_with_content__1.txt
- tests/Commands/__snapshots__/TestMakeCommandTest__test_it_can_change_the_default_unit_namespace_specific__1.txt
- tests/Commands/__snapshots__/TestMakeCommandTest__test_it_generated_correct_feature_file_with_content__1.txt
- tests/Commands/__snapshots__/TestMakeCommandTest__test_it_generated_correct_unit_file_with_content__1.txt
Functionalities to generate a well-formatted namespace from paths.
Note:
This pull request doesn't alter any existing workflow. It only adds the ability to generate a proper StudlyCase namespace from paths.
> Path Namespace - generate a well-formatted StudlyCase namespace from paths.

- src/Generators/ModuleGenerator.php
Force the config replacement option for composer 'APP_FOLDER_NAME', to be handled even when its not present.
> enforce config option

- src/Commands/Make/ControllerMakeCommand.php
- src/Commands/stubs/controller.invokable.stub
- tests/Commands/ControllerMakeCommandTest.php
generate an invokable controller class using --invokable or --i options
> Added invokable option into make-controller command

- src/Commands/stubs/controller.invokable.stub
- tests/Commands/__snapshots__/ControllerMakeCommandTest__test_it_generates_an_invokable_controller__1.txt
Fixed an issue when generating controller using `--invokable` or `-i` option
> Fixes Invokable Controller Stub

- src/Generators/ModuleGenerator.php
Update the ModuleGenerator methods DocBlock.
> Update ModuleGenerator methods DocBlock

- src/Commands/Actions/ModelShowCommand.php
Hi,
This pull request refactors the `module:model-show` command to accurately locate models within the correct folder and namespace by removing the `app_folder` from the namespace. 
Additionally, it improves the handling of `MissingArguments` by integrating Laravel prompt feature.
fixed #1930.
> Refactor `module:model-show` Command for Improved Model Detection

- config/config.php
- src/LaravelModulesServiceProvider.php
> fix function name

- src/LaravelModulesServiceProvider.php
Hi,
This pull request fixes the auto-discovery of translation files, ensuring that only enabled modules have their translation files discovered and registered.
> Fix Translation Auto-Discovery for Enabled Modules

- src/Activators/FileActivator.php
- src/LaravelModulesServiceProvider.php
- src/ModuleManifest.php
- tests/LaravelModulesServiceProviderTest.php
Hi,
In this pull request, I've updated the logic to delete disabled modules provider from the manifest file. Additionally, I made some refactors to improve code readability.
fixed #1950
> Update Module manifest handling and improvement

- composer.json
- src/Commands/UpdatePhpunitCoverage.php
- src/Providers/ConsoleServiceProvider.php
- tests/Commands/UpdatePhpunitCoverageTest.php
This will populate phpunit.xml with paths to scan
```xml
<source>
<include>
<directory>./app</directory>
<directory suffix=".php">./Modules/Auth/app/</directory>
<directory suffix=".php">./Modules/Base/app/</directory>
<directory suffix=".php">./Modules/Profile/app/</directory>
</include>
</source>
```
> added command to add enabled modules to code coverage includes

- src/Commands/stubs/views/master.stub
- src/helpers.php
Fixes #1906 #1880
This will also add possibility for the app to have multiple "hot" file simultaneously
> Add parameter for custom hotfile directory

- src/Commands/Publish/PublishConfigurationCommand.php
fixes No publishable resources for tag [config] https://github.com/nWidart/laravel-modules/issues/1966 and https://github.com/nWidart/laravel-modules/issues/1938
> get dynamic path to provider

- src/Generators/ModuleGenerator.php
Hi,
Similar to pull request #1982, when create plain module, also need reset Module Provider to can find modules to continue process.
fix #1998
> fix make plain module

- src/Commands/Actions/ModelPruneCommand.php
Hi,  
This pull request fixes issues with the `module:prune` command and improves model lookup when selecting a module.
> [fix] fix module prune command

- .github/workflows/php.yml
Hi,  
This pull request adds a GitHub Action for PHP Linting using **Laravel Pint**. When a pull request is pushed, the action automatically updates the code style based on the **`pint.json`** configuration.  
This ensures consistent coding standards and improves code quality across the project.  
Thanks!
> Add PHP Linting (Pint) Action to the Package

- src/ModuleManifest.php
Hi,
Fix condition Load Module manifest.
> [fix] fix load modules

- CHANGELOG.md
- README.md
- composer.json
Drop support for Laravel 11 to keep inline with previous releases.
> add support for Laravel 12

- config/config.php
default path for layout needs to generate a components folder.
> fix: update master view path to new component structure

- src/Commands/stubs/scaffold/provider.stub
- tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generate_module_when_provider_is_enable_and_route_provider_is_disable__1.txt
- tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generate_module_when_provider_is_enable_and_route_provider_is_enable__1.txt
- tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generates_api_module_with_resources__1.txt
- tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generates_module_namespace_using_studly_case__1.txt
- tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generates_module_resources__1.txt
- tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generates_web_module_with_resources__1.txt
- tests/Commands/Make/__snapshots__/ModuleMakeCommandTest__test_it_generates_web_module_with_resources_when_adding_more_than_one_option__1.txt
- tests/Commands/Make/__snapshots__/ProviderMakeCommandTest__test_it_can_change_the_default_namespace__1.txt
- tests/Commands/Make/__snapshots__/ProviderMakeCommandTest__test_it_can_change_the_default_namespace_specific__1.txt
- tests/Commands/Make/__snapshots__/ProviderMakeCommandTest__test_it_can_have_custom_migration_resources_location_paths__1.txt
- tests/Commands/Make/__snapshots__/ProviderMakeCommandTest__test_it_generates_a_master_service_provider_with_resource_loading__1.txt
> Hot fixes for mismatch variables
